services:
  database:
    build:
      context: .
      dockerfile: DockerFile
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=pogres
      - POSTGRES_PASSWORD=pogrespass
      - POSTGRES_DB=pogres
      - DB_USER=anibos
      - DB_PASS=anibospass
      - ANIBOS_DATABASE_NAME=anibos
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data: