services:
  database:
    build:
      context: .
      dockerfile: DockerFile
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgresPass
      - POSTGRES_DB=anibos
      - DB_USER=anibos
      - DB_PASS=anibospass
      - ANIBOS_DATABASE_NAME=anibos
    volumes:
      - ./data/db:/pg/data
